去掉一些 不需要的

diff --git a/RiceInstaller b/RiceInstaller
--- a/RiceInstaller
+++ b/RiceInstaller
@@ -16,32 +16,7 @@ CBL=$(tput setaf 4)
 BLD=$(tput bold)
 CNC=$(tput sgr0)
 
-backup_folder=~/.RiceBackup
 date=$(date +%Y%m%d-%H%M%S)
-
-logo () {
-
-    local text="${1:?}"
-    echo -en "
-	               %%%
-	        %%%%%//%%%%%
-	      %%************%%%
-	  (%%//############*****%%
-	%%%%%**###&&&&&&&&&###**//
-	%%(**##&&&#########&&&##**
-	%%(**##*****#####*****##**%%%
-	%%(**##     *****     ##**
-	   //##   @@**   @@   ##//
-	     ##     **###     ##
-	     #######     #####//
-	       ###**&&&&&**###
-	       &&&         &&&
-	       &&&////   &&
-	          &&//@@@**
-	            ..***
-    z0mbi3 Dotfiles\n\n"
-    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
-}
 
 ########## ---------- You must not run this as root ---------- ##########
 
@@ -60,7 +35,6 @@ fi
 
 ########## ---------- Welcome ---------- ##########
 
-logo "Welcome!"
 printf '%s%sThis script will check if you have the necessary dependencies, and if not, it will install them. Then, it will clone my repository in your HOME directory.\nAfter that, it will create a backup of your files, and then copy the new files to your computer.\n\nMy dotfiles DO NOT modify any of your system configurations.\nYou will be prompted for your root password to install missing dependencies and/or to switch to zsh shell if its not your default.\n\nThis script doesnt have the potential power to break your system, it only copies files from my repository to your HOME directory.%s\n\n' "${BLD}" "${CRE}" "${CNC}"
 
 while true; do
@@ -75,15 +49,15 @@ clear
 
 ########## ---------- Install packages ---------- ##########
 
-logo "Installing needed packages.."
 
-dependencias=(alacritty base-devel brightnessctl bspwm dunst feh geany git imagemagick jq \
-			        jgmenu libwebp lsd maim mpc mpd neovim ncmpcpp npm pamixer pacman-contrib \
-			        papirus-icon-theme physlock picom playerctl polybar polkit-gnome python-gobject ranger \
-			        rofi rustup sxhkd ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd \
-			        ttf-joypixels ttf-terminus-nerd ueberzug webp-pixbuf-loader xclip xdg-user-dirs \
-			        xdo xdotool xorg-xdpyinfo xorg-xkill xorg-xprop xorg-xrandr xorg-xsetroot \
-			        xorg-xwininfo zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting)
+dependencias=(kitty base-devel bspwm dunst feh git jq \
+			        jgmenu lsd \
+			        picom polybar polkit-gnome python-gobject ranger \
+			        rofi sxhkd ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd \
+			        ttf-joypixels ttf-terminus-nerd ueberzug xclip xdg-user-dirs \
+			        xdo xdotool \
+			        xorg-xinit xorg zsh \
+                    go)
 
 is_installed() {
     pacman -Q "$1" &> /dev/null
@@ -116,7 +90,6 @@ fi
 
 ########## ---------- Cloning the Rice! ---------- ##########
 
-logo "Downloading dotfiles"
 
 repo_url="https://github.com/gh0stzk/dotfiles"
 repo_dir="$HOME/dotfiles"
@@ -135,8 +108,6 @@ clear
 
 ########## ---------- Backup files ---------- ##########
 
-logo "Backup files"
-
 printf "If you already have a powerful and super Pro NEOVIM configuration, write 'n' in the next question. If you answer 'y' your neovim configuration will be moved to the backup directory.\n\n"
 
 while true; do
@@ -151,79 +122,11 @@ done
 printf "\nBackup files will be stored in %s%s%s/.RiceBackup%s \n\n" "${BLD}" "${CRE}" "$HOME" "${CNC}"
 sleep 10
 
-[ ! -d "$backup_folder" ] && mkdir -p "$backup_folder"
-
-for folder in bspwm alacritty picom rofi eww sxhkd dunst polybar ncmpcpp ranger zsh mpd paru; do
-    if [ -d "$HOME/.config/$folder" ]; then
-        if mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date" 2>> RiceError.log; then
-            printf "%s%s%s folder backed up successfully at %s%s/%s_%s%s\n" "${BLD}" "${CGR}" "$folder" "${CBL}" "$backup_folder" "$folder" "$date" "${CNC}"
-            sleep 1
-        else
-            printf "%s%sFailed to backup %s folder. See %sRiceError.log%s\n" "${BLD}" "${CRE}" "$folder" "${CBL}" "${CNC}"
-            sleep 1
-        fi
-    else
-        printf "%s%s%s folder does not exist, %sno backup needed%s\n" "${BLD}" "${CGR}" "$folder" "${CYE}" "${CNC}"
-        sleep 1
-    fi
-done
-
-if [[ $try_nvim == "y" ]]; then
-        # Download nvim
-    if [ -d "$HOME/.config/nvim" ]; then
-        if mv "$HOME/.config/nvim" "$backup_folder/nvim_$date" 2>> RiceError.log; then
-                printf "%s%snvim folder backed up successfully at %s%s/nvim_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "$date" "${CNC}"
-                sleep 1
-            else
-                printf "%s%sFailed to backup nvim folder. See %sRiceError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
-                sleep 1
-        fi
-        else
-            printf "%s%snvim folder does not exist, %sno backup needed%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
-            sleep 1
-    fi
-fi
-
-for folder in "$HOME"/.mozilla/firefox/*.default-release/chrome; do
-    if [ -d "$folder" ]; then
-        if mv "$folder" "$backup_folder"/chrome_"$date" 2>> RiceError.log; then
-            printf "%s%sChrome folder backed up successfully at %s%s/chrome_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "${date}" "${CNC}"
-        else
-            printf "%s%sFailed to backup Chrome folder. See %sRiceError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
-        fi
-    else
-        printf "%s%sThe folder Chrome does not exist, %sno backup needed%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
-    fi
-done
-
-for file in "$HOME"/.mozilla/firefox/*.default-release/user.js; do
-    if [ -f "$file" ]; then
-        if mv "$file" "$backup_folder"/user.js_"$date" 2>> RiceError.log; then
-            printf "%s%suser.js file backed up successfully at %s%s/user.js_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "${date}" "${CNC}"
-        else
-            printf "%s%sFailed to backup user.js file. See %sRiceError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
-        fi
-    else
-        printf "%s%sThe file user.js does not exist, %sno backup needed%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
-    fi
-done
-
-if [ -f ~/.zshrc ]; then
-    if mv ~/.zshrc "$backup_folder"/.zshrc_"$date" 2>> RiceError.log; then
-        printf "%s%s.zshrc file backed up successfully at %s%s/.zshrc_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "${date}" "${CNC}"
-    else
-        printf "%s%sFailed to backup .zshrc file. See %sRiceError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
-    fi
-else
-    printf "%s%sThe file .zshrc does not exist, %sno backup needed%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
-fi
-
 printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 5
 
 ########## ---------- Copy the Rice! ---------- ##########
 
-logo "Installing dotfiles.."
 printf "Copying files to respective directories..\n"
 
 [ ! -d ~/.config ] && mkdir -p ~/.config
@@ -279,22 +182,21 @@ fc-cache -rv >/dev/null 2>&1
 printf "\n\n%s%sFiles copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 5
 
-########## ---------- Installing Paru & others ---------- ##########
+########## ---------- Installing Yay & others ---------- ##########
 
-logo "installing Paru, Eww, tdrop & xqp"
-
-# Installing Paru
-if command -v paru >/dev/null 2>&1; then
-    printf "%s%sParu is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
+# Installing Yay
+if command -v yay >/dev/null 2>&1; then
+    printf "%s%sYay is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 else
-    printf "%s%sInstalling paru%s\n" "${BLD}" "${CBL}" "${CNC}"
+    printf "%s%sInstalling yay%s\n" "${BLD}" "${CBL}" "${CNC}"
     {
         cd "$HOME" || exit
-        git clone https://aur.archlinux.org/paru-bin.git
-        cd paru-bin || exit
+        git clone https://aur.archlinux.org/yay.git
+        cd yay || exit
+        go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
         makepkg -si --noconfirm
-        } || {
-        printf "\n%s%sFailed to install Paru. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
+    } || {
+        printf "\n%s%sFailed to install Yay. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
     }
 fi
 
@@ -303,15 +205,7 @@ if command -v tdrop >/dev/null 2>&1; then
     printf "\n%s%sTdrop is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 else
     printf "\n%s%sInstalling tdrop, this should be fast!%s\n" "${BLD}" "${CBL}" "${CNC}"
-    paru -S tdrop-git --skipreview --noconfirm
-fi
-
-# Intalling xqpp
-if command -v xqp >/dev/null 2>&1; then
-    printf "\n%s%sxqp is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
-else
-    printf "\n%s%sInstalling xqp, this should be fast!%s\n" "${BLD}" "${CBL}" "${CNC}"
-    paru -S xqp --skipreview --noconfirm
+    yay -S tdrop-git --skipreview --noconfirm
 fi
 
 # Installing Eww
@@ -320,46 +214,15 @@ if command -v eww >/dev/null 2>&1; then
 else
     printf "\n%s%sInstalling Eww, this could take 10 mins or more.%s\n" "${BLD}" "${CBL}" "${CNC}"
     {
-        sudo pacman -S rustup --noconfirm
+        yay -S eww --skipreview --noconfirm
         cd "$HOME" || exit
-        git clone https://github.com/elkowar/eww
-        cd eww || exit
-        cargo build --release --no-default-features --features x11
-        sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
-        cd "$HOME" || exit
-        rm -rf {paru-bin,.cargo,.rustup,eww}
+        rm -rf {yay}
         } || {
         printf "\n%s%sFailed to install Eww. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
     }
 fi
 
-########## ---------- Enabling MPD service ---------- ##########
 
-logo "Enabling mpd service"
-
-# Verifica si el servicio mpd está habilitado a nivel global (sistema)
-if systemctl is-enabled --quiet mpd.service; then
-    printf "\n%s%sDisabling and stopping the global mpd service%s\n" "${BLD}" "${CBL}" "${CNC}"
-    sudo systemctl stop mpd.service
-    sudo systemctl disable mpd.service
-fi
-
-printf "\n%s%sEnabling and starting the user-level mpd service%s\n" "${BLD}" "${CYE}" "${CNC}"
-systemctl --user enable --now mpd.service
-
-printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-sleep 2
 
 ########## --------- Changing shell to zsh ---------- ##########
 
-logo "Changing default shell to zsh"
-
-if [[ $SHELL != "/usr/bin/zsh" ]]; then
-    printf "\n%s%sChanging your shell to zsh. Your root password is needed.%s\n\n" "${BLD}" "${CYE}" "${CNC}"
-    # Cambia la shell a zsh
-    chsh -s /usr/bin/zsh
-    printf "%s%sShell changed to zsh. Please reboot.%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-else
-    printf "%s%sYour shell is already zsh\nGood bye! installation finished, now reboot%s\n" "${BLD}" "${CGR}" "${CNC}"
-fi
-zsh
